### ISSUE TITLE
Jsonbody param dosen't handle kotlin List

### ISSUE THREAD

**Issue by AndreasSM** [jhannes/action-controller#11]
https://github.com/jhannes/action-controller/blob/e26480998a82da658d03f0284fb331fb5a58c31d/action-controller/src/main/java/org/actioncontroller/TypesUtil.java#L27

This function is used to determine whether incomming json is an array or object. This does not work for kotlin List object. i.e:

```
@Put("/path")
fun resourcePut(
    @JsonBody resourceDto: List<resourceDto>
){
….
}
```

**Comment by jhannes** [comment]
This is unlikely to work at any rate. JsonBuddy creates Lists and Sets with Collectors.toList() and Collectors.toSet() and there is no generic way to construct kotlin.collections.List when Kotlin is not on the compile classpath. Perhaps a custom annotation is the only way?

I have simplified https://github.com/jhannes/action-controller/blob/master/action-controller/src/main/java/org/actioncontroller/json/JsonBody.java to make it easier to see what's needed for a custom version. I'm also working on a release of JsonBuddy which may support this better
