### ISSUE TITLE
Should map requests to methods even though there is a potential for conflict

### ISSUE THREAD

**Issue by Andreas2S** [jhannes/action-controller#18]
Some APIs come with a certain amount of ambiguity. For instance, one might have the following scenario:

GET /users/{uid}/roles
GET /users/roles/{role}

where the first endpoint returns the roles of a specific user, while the second searches for users with a spesific role

**Current situastion**:
One cannot handle this in Action-controller due to error "throw new ActionControllerConfigurationException(action + " is in conflict with " + existingAction);"

**Behaviour in spring:**
Spring has one way of handling these situations: https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-requestmapping-pattern-comparison

- It does not throw any error up front, yet tries to map each request at runtime  ("/users/abc/roles" goes to the first, while "/users/roles/abc" to the second)
-In case of a url that applies equaly to both ("/users/roles/roles", a 403 error is thrown)

Given the following case:
1. /a/{b}/c
2. /a/{b}/{c}
Spring would not throw any error if you try "/a/b/c", but instead regard the first method as "more specific" due to the fact that is only contains one variable, while method two has two variables

**Expected behaviour in action-controller:**
I would expect action-controller to at least handle the same cases as spring does with regards to determining a method in order to replace existing systems without changes in the API sepc  (that is, try runtime to determine a method rather than to throw a "potential conflict"-error )

Either throw an error when no method can be determined by the "most specific" rule, or to let the one with the longest constant prefix prevail.

**Comment by jhannes** [comment]
I refactored the routing to support this. But it's pretty duplicated. Do you have input on how to improve the code before I release it, @Andreas2S ?

https://github.com/jhannes/action-controller/commit/4e9b719da66f18cf1ad351891b6bf31b1d611544#diff-1b6b762ae28a7eaf0533117de21d709e15ee05c63e6dc59cb5f26b26dc435f14

**Comment by jhannes** [comment]
Resolved in version 0.0.29
